/**
 * Intrinsic dimensions of every bundled image under /public/assets.
 *
 * next/image needs width and height to reserve layout space before the file
 * arrives, which is what keeps Cumulative Layout Shift at zero. Keeping them in
 * a generated map means markup does not have to repeat numbers that can drift
 * out of sync with the files.
 *
 * Generated by scripts/generate-image-manifest.mjs - do not edit by hand.
 * Regenerate after adding or replacing an asset:
 *   npm run images:manifest
 */
export type ImageSize = { width: number; height: number };

export const IMAGE_SIZES: Record<string, ImageSize> = {
  "/assets/abcn/abcn-emblem.png": { width: 684, height: 692 },
  "/assets/abcn/abcn-logo.png": { width: 704, height: 254 },
  "/assets/abcn/collaborators.png": { width: 1120, height: 1296 },
  "/assets/abcn/community-connection.jpg": { width: 1600, height: 1067 },
  "/assets/abcn/ecosystem-network.png": { width: 1376, height: 784 },
  "/assets/abcn/harmonie-essome-official.jpg": { width: 643, height: 1072 },
  "/assets/abcn/harmonie-essome-portrait.png": { width: 643, height: 1072 },
  "/assets/abcn/harmonie-essome.png": { width: 643, height: 1072 },
  "/assets/abcn/innovators-summit.jpg": { width: 2400, height: 1600 },
  "/assets/fiali/female-founder-vision.jpg": { width: 864, height: 1248 },
  "/assets/fiali/female-founder-workshop.jpg": { width: 1120, height: 1296 },
  "/assets/fiali/female-founders-summit.jpg": { width: 2400, height: 1600 },
  "/assets/fiali/fiali-hero-banner.jpg": { width: 1376, height: 784 },
  "/assets/fiali/growth-lab-session.jpg": { width: 2400, height: 1600 },
  "/assets/fiali/logos/abcn.png": { width: 288, height: 113 },
  "/assets/fiali/logos/black-women-in-tech-dach.png": { width: 188, height: 209 },
  "/assets/fiali/logos/divoc-rising.png": { width: 356, height: 216 },
  "/assets/fiali/logos/flourish-prosper.png": { width: 401, height: 126 },
  "/assets/fiali/logos/frankfurt-forward.png": { width: 441, height: 96 },
  "/assets/fiali/logos/kompass-frankfurt.png": { width: 599, height: 120 },
  "/assets/fiali/logos/wirtschaftsfoerderung-frankfurt.png": { width: 360, height: 140 },
  "/assets/fiali/partners-strip.jpg": { width: 900, height: 114 },
};

/** Dimensions for a bundled asset, or undefined for remote/CMS images. */
export function imageSize(src: string): ImageSize | undefined {
  return IMAGE_SIZES[src];
}
