/**
 * Intrinsic dimensions of every bundled image under /public/assets.
 *
 * next/image needs width and height to reserve layout space before the file
 * arrives, which is what keeps Cumulative Layout Shift at zero. Keeping them in
 * a generated map means markup does not have to repeat numbers that can drift
 * out of sync with the files.
 *
 * Generated by scripts/generate-image-manifest.mjs - do not edit by hand.
 * Regenerate after adding or replacing an asset:
 *   npm run images:manifest
 */
export type ImageSize = { width: number; height: number };

export const IMAGE_SIZES: Record<string, ImageSize> = {
  "/assets/abcn/abcn-emblem.png": { width: 684, height: 692 },
  "/assets/abcn/abcn-logo.png": { width: 704, height: 254 },
  "/assets/abcn/events/afropean-team-outdoors.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/afropean-women-celebration.jpg": { width: 1248, height: 784 },
  "/assets/abcn/events/alumni-community-group.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/alumni-welcome-stage.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/audience-listening-session.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/business-conference-audience.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/business-development-talk.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/cafe-networking-space.jpg": { width: 1150, height: 1534 },
  "/assets/abcn/events/colourful-community-group.jpg": { width: 1064, height: 1600 },
  "/assets/abcn/events/community-circle-conversation.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/community-mixer-welcome.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/community-team-portrait.jpg": { width: 2000, height: 1500 },
  "/assets/abcn/events/conference-audience-hall.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/conference-listening-room.jpg": { width: 1229, height: 1536 },
  "/assets/abcn/events/ecosystem-mapping-roundtable.jpg": { width: 2000, height: 1500 },
  "/assets/abcn/events/evening-social-gathering.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/female-founders-lineup.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/fireside-session-room.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/fireside-stage-keynote.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/founder-conversation-spotlight.jpg": { width: 1333, height: 2000 },
  "/assets/abcn/events/founder-question-moment.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/frankfurt-skyline-street.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/friends-welcome-moment.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/gallery-evening-thumbs-up.jpg": { width: 1601, height: 2000 },
  "/assets/abcn/events/hall-keynote-audience.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/harmonie-essome-speaking.jpg": { width: 1333, height: 2000 },
  "/assets/abcn/events/harmonie-programme-lead.jpg": { width: 1000, height: 1333 },
  "/assets/abcn/events/international-womens-day.jpg": { width: 607, height: 1080 },
  "/assets/abcn/events/mentorship-conversation.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/networking-evening-group.jpg": { width: 2000, height: 1328 },
  "/assets/abcn/events/networking-fair-pair.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/panel-discussion-hall.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/peer-circle-women.jpg": { width: 1600, height: 2000 },
  "/assets/abcn/events/rooftop-community-gathering.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/rooftop-terrace-group.jpg": { width: 1227, height: 1534 },
  "/assets/abcn/events/sales-lab-workshop-room.jpg": { width: 1600, height: 2000 },
  "/assets/abcn/events/salon-conversation-circle.jpg": { width: 1500, height: 2000 },
  "/assets/abcn/events/salon-fireside-conversation.jpg": { width: 1272, height: 720 },
  "/assets/abcn/events/womens-network-meetup.jpg": { width: 1284, height: 1605 },
  "/assets/abcn/events/workshop-listening-session.jpg": { width: 2000, height: 1333 },
  "/assets/abcn/events/workshop-participants-listening.jpg": { width: 1600, height: 1064 },
  "/assets/abcn/harmonie-essome-official.jpg": { width: 643, height: 1072 },
  "/assets/abcn/share-fiali.jpg": { width: 1200, height: 630 },
  "/assets/fiali/logos/abcn.png": { width: 288, height: 113 },
  "/assets/fiali/logos/black-women-in-tech-dach.png": { width: 188, height: 209 },
  "/assets/fiali/logos/divoc-rising.png": { width: 356, height: 216 },
  "/assets/fiali/logos/flourish-where-planted.png": { width: 453, height: 520 },
  "/assets/fiali/logos/frankfurt-forward.png": { width: 441, height: 96 },
  "/assets/fiali/logos/kompass-frankfurt.png": { width: 599, height: 120 },
  "/assets/fiali/logos/wirtschaftsfoerderung-frankfurt.png": { width: 360, height: 140 },
};

/** Dimensions for a bundled asset, or undefined for remote/CMS images. */
export function imageSize(src: string): ImageSize | undefined {
  return IMAGE_SIZES[src];
}
